# Generated by Django 4.1.4 on 2022-12-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_registro_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cargo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cartao',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
    ]
